#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
( cat <<_USER_\SCRIPT_
#!/bin/bash

export SCRAM_ARCH=slc6_amd64_gcc481
cd /afs/cern.ch/user/k/ktos/BBA/CMSSW_7_1_11_patch2/src
eval `scramv1 runtime -sh`
cd -
source /afs/cern.ch/cms/caf/setup.sh 
mv /afs/cern.ch/user/k/ktos/BBA/CMSSW_7_1_11_patch2/src/BBA/Generation/NMSSM_ggH_a9_10K_Events_v1/ggHaaSampleGenerator_610.* . 
cmsRun ggHaaSampleGenerator_610.py
cmsStage -f NMSSM_a9_ggH_610.root /store/user/ktos/NMSSM_ggH_a9_10K_Events_v1
rm ggHaaSampleGenerator_610.*  NMSSM_a9_ggH_610.root*
if [ -e RandomEngineState_610.log ]
    then
    rm RandomEngineState_610.log*
fi
if [ -e histProbFunction_610.root ]
    then
    rm histProbFunction_610.root*
fi

exit 0

_USER_SCRIPT_
) > $LSB_CHKFILENAME.shell
chmod u+x $LSB_CHKFILENAME.shell
/usr/local/lsf/etc/job_starter '$LSB_JOBFILENAME.shell'
saveExit=$?
/bin/rm -f $LSB_JOBFILENAME.shell
(exit $saveExit)

ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
